

server
{
    listen 443 ssl;
    listen [::]:443 ssl;

    ssl_certificate /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    resolver 8.8.8.8; 
    # Google DNS it helps to resolve the backend service name, for example with the backend service name "auth" it will resolve to the correct IP address of the auth service in the Docker network.
    server_name localhost;

    location / {
        proxy_pass http://auth:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /static/ {
        alias /app/static/;
    }

    location /help/
    {
        alias /app/help/;
    }
}
